# version属性は廃止されたので削除
services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/mcp/app/src
      - home-volume:/home/mcp
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  home-volume:
